### ISSUE TITLE
test_data error

### ISSUE THREAD

**Issue by stinky-kombucha-labs** [patriotyk/narizaka#13]
After installing via "git clone https://github.com/patriotyk/narizaka.git
pip install -e narizaka/" I tried to run with test data but got an error.  
Can you please help with this issue? My system is Ubuntu 24, and there were no errors during installation, I tried reinstalling several times but got the same thing every time

Error:
`# narizaka test_data/farshrutka 
The following books have been found:

Partially or not transcribed:
None test_data/farshrutka/Farshrutka.fb2
Transcribing:   0%|                                                                                                                                                                       | 0/1 [00:00<?, ?it/s]Process BackendWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/user/Documents/code/narizaka/narizaka/transcriber.py", line 28, in run
    result = self.backend.transcribe(book_files[1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/code/narizaka/narizaka/asr_backends/faster_whisper.py", line 27, in transcribe
    result = self.model.transcribe_stable(filename_16, language='uk', regroup=True, verbose=None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/code/new_narizaka_venv/lib/python3.12/site-packages/stable_whisper/whisper_word_level/faster_whisper.py", line 150, in faster_transcribe
    return transcribe_any(
           ^^^^^^^^^^^^^^^
  File "/home/user/Documents/code/new_narizaka_venv/lib/python3.12/site-packages/stable_whisper/non_whisper.py", line 343, in transcribe_any
    result = inference_func(**inference_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/code/new_narizaka_venv/lib/python3.12/site-packages/stable_whisper/whisper_word_level/faster_whisper.py", line 202, in _inner_transcribe
    segment['words'] = [w._asdict() for w in words]
                        ^^^^^^^^^
AttributeError: 'dict' object has no attribute '_asdict'

Transcribing:   0%|                                                                                                                                                                       | 0/1 [00:20<?, ?it/s]`

**Comment by patriotyk** [comment]
Looks like stable-ts package version issue. Could you run `pip freeze | grep stable` in your env and show me output?

**Comment by patriotyk** [comment]
No this is faster-whisper update issue. https://github.com/jianfch/stable-ts/commit/fe00aaf2bd64603decb4c01557b1d39431809793 as you can see this commit fixes issue. So you can just try to upgrade stable-ts.
